### ISSUE TITLE
Add Readme

### ISSUE THREAD

**Issue by after-ephemera** [azjkjensen/sudoku-validator#1]
Add a readme describing functionality.

**Comment by Anirudh257** [comment]
Hi, I am a rookie. I would love to contribute to this issue and help you out. Can I get assigned to this issue.

**Comment by after-ephemera** [comment]
@Anirudh257 have at it! Can you just edit the existing readme and give a pseudocode description of the code as well as a brief description of the approach taken?

**Comment by Anirudh257** [comment]
Sorry for this late reply. I will make the required changes.

**Comment by Anirudh257** [comment]
I have made the changes. Please tell me if I have done it correctly or does it require any change.
